pid /var/cache/nginx/nginx.pid;

worker_processes auto;
events {
    worker_connections 1024;
}
http {
    server {
        # Listen on an unprivileged port so non-root users can start it
        listen 8080;
        server_name localhost;

        # Serve static frontend files
        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ =404;
        }

        # Reverse Proxy for API routes
        location /jobs {
            proxy_pass http://api:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # location /status {
        #     proxy_pass http://api:8000/jobs/;
        #     proxy_set_header Host $host;
        #     proxy_set_header X-Real-IP $remote_addr;
        # }
    }
}